### ISSUE TITLE
Fix the the display of some countries on the map, please

### ISSUE THREAD

**Issue by GButrik** [antonlukin/2019-nCoV#16]
Good afternoon!

Could you please correct the display of some countries on your map? For example, the Czech Republic. They confirmed cases of infection long ago, but on the map it’s not red.

In addition, there are countries that I select in the list of infected regions, but they are not highlighted on the map:

• Singapore
• Hong Kong
• Kuwait
• Bahrain
• Macau
• San Marino
• Qatar
• Czech Republic
• Andorra
• Liechtenstein
• Luxembourg
• Monaco

**Comment by antonlukin** [comment]
Hello. Thanks for your report.
The main reason is that the detailed map has large size (~ 1-2MB). 
I think this is not suitable for downloading on mobile devices. 

Besides this, part of your examples are already on the map:
- Kuwait
- Qatar
- Luxembourg

I've already fixed the problem with Czech Republic, thanks.

**Comment by GButrik** [comment]
Thanks for fixing the Czech Republic! :)

You're right, I was able to find individual countries on the map in red when choosing:
• Kuwait
• Qatar
• Luxembourg

But the rest, alas, did not work out. By the way, I use a PC, not a mobile device. **Hence the question - maybe you can make a certain strip of zooming in (or, even better, so that the scale can be changed with the mouse wheel)?**

Probably, then I can see all the countries that are currently unavailable for viewing with a separate choice.

**Comment by antonlukin** [comment]
Ok, I understand your point. Thank you

**Comment by GButrik** [comment]
Could you please fix Bosnia now?
It's not displaying too...

**Comment by GButrik** [comment]
Fix Moldova and Montenegro, pls.
They were infected yesterday.

**Comment by GButrik** [comment]
Moldova+Turkey are not displaying as infected.
But they are... :(

**Comment by GButrik** [comment]
Now Russia+Northern Ireland+Great Britain are broken :(

**Comment by xDragonZ** [comment]
Here's another up to date source https://www.worldometers.info/coronavirus/#countries

**Comment by xDragonZ** [comment]
Here's another up to date source.
Maybe dev can crawl this instead?

https://www.worldometers.info/coronavirus/#countries
