### ISSUE TITLE
No data on the map for China

### ISSUE THREAD

**Issue by Den-dp** [antonlukin/2019-nCoV#20]
![image](https://user-images.githubusercontent.com/1770529/76332772-78208f80-62f9-11ea-9f80-02ce92c1851e.png)
![image](https://user-images.githubusercontent.com/1770529/76332860-89699c00-62f9-11ea-8c7f-7f5ed9107a02.png)

**Comment by GButrik** [comment]
+ Plus no data for Serbia, Panama, Mongolia.
What's happened?

**Comment by antonlukin** [comment]
I have to change data source to fix all this problems
