### ISSUE TITLE
TELEGRAM ERROR

### ISSUE THREAD

**Issue by xrustikmirr** [antonlukin/2019-nCoV#3]
Make the information in the telegram as a picture. When viewing from a phone or tablet, nothing is clear.

![Screenshot_20200126-213507](https://user-images.githubusercontent.com/60324957/73139880-a1f06080-4083-11ea-8202-a3017ea89fe2.png)

**Comment by antonlukin** [comment]
It depends on the font size. Any ideas how to write differently?
Maybe this way:

```
China 2064 / 56 / 49
```

or 
```
China:
2064 / 56 / 49

Thailand
8 / 0 / 5
```

**Comment by antonlukin** [comment]
I changed the size of the columns. Let's see what happens

**Comment by xrustikmirr** [comment]
> I changed the size of the columns. Let's see what happens

It's OK, thank you! :)

**Comment by xrustikmirr** [comment]
> I changed the size of the columns. Let's see what happens

But the repost on the iPhone looks like this. Everything is good on android.

![image](https://user-images.githubusercontent.com/60324957/73140432-e2eb7380-4089-11ea-96a2-9bbd44ce2973.png)

**Comment by antonlukin** [comment]
Well, I'll try to find another wat to fix it.

**Comment by lanpai** [comment]
I think the most reliable way to do this would be to do
```
Region
Cases/Deaths/Cured

China
2068+/56/49
...
```
because that'll compact it horizontally the most as well as prevent some apps from trying to line break it due to a lack of spaces.

**Comment by antonlukin** [comment]
Since the data source deleted the fourth column, I think it's not necessary to show table header.
So let's try this version:

![image](https://user-images.githubusercontent.com/454185/73171353-2352fc00-4133-11ea-8a44-9419c18ad646.png)
