### ISSUE TITLE
[Feature Request] Can we have a timeline of infected people on the website?

### ISSUE THREAD

**Issue by calvinchankf** [antonlukin/2019-nCoV#5]
so that the users would be able to read the latest numbers as well as the past figures on https://coronavirus.zone/

**Comment by antonlukin** [comment]
I don't know how to design it. Any ideas?
For now you can use telegram channel https://t.me/coronavirus_outbreak to see the changes.

**Comment by balalamba** [comment]
Hey, I made it using Google Datastudio.  So anyone can use and share, I will share my Datastudio Connector and you will be able create yours own dashboards.
https://datastudio.google.com/u/1/reporting/078c25fe-d721-4697-91d6-ddc94372ed0e/page/DQBDB

**Comment by calvinchankf** [comment]
> Hey, I made it using Google Datastudio. So anyone can use and share, I will share my Datastudio Connector and you will be able create yours own dashboards.
> https://datastudio.google.com/u/1/reporting/078c25fe-d721-4697-91d6-ddc94372ed0e/page/DQBDB

@olegpopovskiy It looks good!!! but i see that the last update is jan31 2020, can we make it a little bit more update-to-date? how do u connect the data here to google datastudio?

**Comment by balalamba** [comment]
Calvin, CRON process add new data each 6 hours, I don't know any source which gives a new data more often.
World Health Organization updates post a new "pdf" rapport just once a day, so I think 6 hours is relevant.

How it works: Datastudio dashboard updates itself automatically through Datastudio Connector (just a Google Script) that grab data from db. I made 2 Datastudio Connectors, one gives only the last values, the second gives all available history.

Actual state: https://datastudio.google.com/datasources/cda8ed00-4a50-45ee-8fe7-e77e9ca35dd9
Timeline https://datastudio.google.com/datasources/2a9eb533-1a4d-4154-9445-63933c6e01e0

So you can create your own dashboard, share and embed it on website. @antonlukin
