### ISSUE TITLE
Feature request: Recovered Counter

### ISSUE THREAD

**Issue by sergstepanenko** [antonlukin/2019-nCoV#6]
Can we have "Recovered Counter" as [here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR1GJMlW-AweIgAgs0wOmkshtMMnupZEWO4AIFY1lPyvXU11YbhC8KS4bYA#/bda7594740fd40299423467b48e9ecf6)?

**Comment by antonlukin** [comment]
To do this, I need to rebuild the parser to a new data source. Maybe do it.
